.\" Process this file with
.\" groff -man -Tascii nstk.1
.\"
.TH nse 1 "APRIL 2011" Linux "User Manuals"
.SH NAME
nse \- ns in emulation mode to emulate real network
.SH SYNOPSIS
.na
.B ns
[
.I file
[
.I arg arg ...
]
]
.ad
.SH DESCRIPTION
.B nstk
is same as ns,but in emulation mode.

See ns (1) for more details.

.SH AUTHOR
YunQiang Su <wzssyqa@gmail.com>

.SH "SEE ALSO"
.BR ns (1) nstk (1)
