.\" Process this file with
.\" groff -man -Tascii nstk.1
.\"
.TH nstk 1 "APRIL 2010" Linux "User Manuals"
.SH NAME
nstk \- ns with tk support
.SH SYNOPSIS
.na
.B ns
[
.I file
[
.I arg arg ...
]
]
.ad
.SH DESCRIPTION
.B nstk
is same as ns,but with tk GUI support.

See ns (1) for more details.

.SH AUTHOR
YunQiang Su <wzssyqa@gmail.com>

.SH "SEE ALSO"
.BR ns (1) nse (1)
